### PR TITLE
Rollback depending on pwd

### PR DESCRIPTION
**Pull request by balmasea**

### CODE REVIEW

**Comment by balmasea** [comment]
@shakefu @jvanderaa @mundruid 
I'm getting this from travis result: 
`The job exceeded the maximum log length, and has been terminated.`
Is there something wrong with travis? As far as I see, tests are passing, aren't they?

**Comment by jmcgill298** [comment]
@balmasea does using `_get_file_system()` work?

**Comment by balmasea** [comment]
> _get_file_system

yeah, that's better! thanks

**Comment by jmcgill298** [comment]
@balmasea can you add `venv` to the exclude list in the pyproject.toml file?




[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
  \.git
| \.tox
| \.venv
| _build
| buck-out
| build
| dist
| blib2to3
| tests/data
)/
'''

**Review by jmcgill298 — APPROVED** [review]
Thanks @balmasea

**Pull request merged**
